[server]
runOnSave = false

[runner]
fileWatcherType = "poll"
excludedWatchPaths = [
  "venv/*",
  "env/*",
  "*/site-packages/*",
  # You can even target torch explicitly:
  "**/site-packages/torch/**"
]
